### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by youha6149** [youha6149/path-chronicle#1]
- [x] #8
- [x] feature: 一覧機能の作成
- [x] feature: 削除機能の作成 
- [x] feature: CSVに記録されたサブパスを持つディレクトリを削除したとき、そのサブパスがCSVに残らないようにする
- [x] test: FsoExpansionインスタンス生成時にcsvがない場合もあるので、その場合のテストも作る
- [x] #5
- [ ] csv記録処理を別モジュールに分けるか検討
- [x] #9
- [x] csv_root_dirやmodule_root_dirはコンストラクタや関数内で定義しているが、それだと、get_package_rootと密結合ではないか？->csv_root_dir外部からのみ指定できるようにするべき？
- [x] #2 
- [x] pip install したときにpoetryのscriptsで使用しているパスが環境によって変えることができるか調べる
- [x] 検討用のissueテンプレートを作成する
- [x] paths辞書の保存形式の変更(今 パス名: パス -> id: id, name: パス名, path: パス)

以下の二つに関しては[#8 ]に統合した方が良い
- [x] #6
- [x] #3
